package io.zero.db.dao;

import io.zero.db.entity.Good;
import io.zero.db.entity.GoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    long countByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int deleteByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    Good selectOneByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    Good selectOneByExampleSelective(@Param("example") GoodExample example, @Param("selective") Good.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    List<Good> selectByExampleSelective(@Param("example") GoodExample example, @Param("selective") Good.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    List<Good> selectByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    Good selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Good.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    Good selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<Good> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<Good> list, @Param("selective") Good.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int upsert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int upsertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int batchUpsert(@Param("list") List<Good> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int batchUpsertSelective(@Param("list") List<Good> list, @Param("selective") Good.Column ... selective);
}